### ISSUE TITLE
windows: pkg-config and dpdk

### ISSUE THREAD

**Issue by williamtu** [smadaminov/ovs-dpdk-meson-issues#38]
looks like pkg-config can find libdpdk after setting the PKG_CONFIG_PATH
```shell
PS C:\ovs-meson> pkg-config.exe --libs dpdk
Package dpdk was not found in the pkg-config search path.
Perhaps you should add the directory containing `dpdk.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dpdk' found
PS C:\ovs-meson> pkg-config.exe --libs libdpdk
-LC:/TEMP/dpdk/lib -Wl,--as-needed -lrte_pdump -lrte_latencystats -lrte_gso -lrte_gro -lrte_cfgfile -lrte_bitratestats -lrte_time
r -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ri
ng -lrte_eal -lrte_telemetry -lrte_kvargs
PS C:\ovs-meson> pkg-config.exe --list-al
Unknown option --list-al
PS C:\ovs-meson> pkg-config.exe --list-all
libdpdk      DPDK - The Data Plane Development Kit (DPDK).
libdpdk-libs dpdk-libs - Internal-only DPDK pkgconfig file. Not for direct use.
PS C:\ovs-meson> pkg-config.exe --cflags libdpdk
-include rte_config.h -march=native -IC:/TEMP/dpdk/include
```

but meson can not find it
```meson
 dpdk_lib = cc.find_library('dpdk')
 dpdk_lib = cc.find_library('dpdk', dirs: ['C:\\temp\\dpdk\\lib'])
```

**Comment by vipinpv85** [comment]
on Windows environment, I assume you have installed 'C:\\temp\\dpdk\\lib'. I got the pkg-config.exe working by 2 moths

1. adding prefix PKG_CONFIG_PATH=C:\temp\dpdk\lib\pkg-config\ pkg-config --cflags libdpdk
2. changing the desired path dependency in meson as ` dpdk_lib = cc.find_library('dpdk', dirs: ['C:\\temp\\dpdk\\lib\\pkg-config'])`

**Comment by vipinpv85** [comment]
> Thanks for the information!
> 
> Another way suggested by Bruce is to use -Dpkg_config_path.
> 
> ```
> PS C:\k8s-antrea-dpdk-win\ovs> meson --reconfigure build
> -Dpkg_config_path=C:\temp\dpdk\lib\pkgconfig\
> ```
> 
> discussed here:
> http://inbox.dpdk.org/dev/CALDO+SY28rpwQCu08AyFy5uX4+T1=09tvNoZQS3j6Mbzm_nHqQ@mail.gmail.com/

good to hear, if the problem is resolved please feel free to close the ticket
