### ISSUE TITLE
dpdk windows: missing queue.h

### ISSUE THREAD

**Issue by williamtu** [smadaminov/ovs-dpdk-meson-issues#46]
In file included from ../lib/dpdk.c:27:
C:\temp\dpdk\include\rte_log.h:24:10: fatal error: 'sys/queue.h' file not found
#include <sys/queue.h>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.

**Comment by vipinpv85** [comment]
For DPDK version `21.05 windows deployment`  the file `sys/queue.h` is present in `DPDK root folder\lib\eal\windows\include\`
