### ISSUE TITLE
Missing directory error

### ISSUE THREAD

**Issue by ua1422** [smadaminov/ovs-dpdk-meson-issues#58]
Build failing due to following missing directories:

mkdir C:\pthreads\pthreads4w_source/include
mkdir C:\pthreads\pthreads4w_source/lib

C:\Users\Usman Ansari\source\ovs-dpdk-meson\ovs>meson build -Dwith-pthread=C:\pthreads\pthreads4w
The Meson build system
Version: 0.59.1
Source dir: C:\Users\Usman Ansari\source\ovs-dpdk-meson\ovs
Build dir: C:\Users\Usman Ansari\source\ovs-dpdk-meson\ovs\build
Build type: native build
Project name: openvswitch
Project version: 2.16.90
C compiler for the host machine: clang (clang 12.0.1 "clang version 12.0.1")
C linker for the host machine: clang link 14.29.30133.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program C:\Users\Usman Ansari\AppData\Local\Programs\Python\Python38\python found: YES (C:\Users\Usman Ansari\AppData\Local\Programs\Python\Python38\python.exe)
Library pthreadVC3-w32 found: YES
Library Ws2_32 found: YES
Library WbemUuid found: YES
Library Shlwapi found: YES
Library Iphlpapi found: YES
Has header "bits/floatn/common.h" : NO
Has header "dlfcn.h" : NO
Has header "inttypes.h" : YES
Has header "libunwind.h" : NO
Has header "linux/if/ether.h" : NO
Has header "linux/net/namespace.h" : NO
Has header "linux/perf/event.h" : NO
Has header "linux/types.h" : NO
Has header "memory.h" : YES
Has header "mntent.h" : NO
Has header "net/if/mib.h" : NO
Has header "linux/netlink.h" : NO
Has header "rte/config.h" : NO
Has header "stdatomic.h" : YES
Has header "stdint.h" : YES
Has header "stdio.h" : YES
Has header "stdlib.h" : YES
Has header "strings.h" : NO
Has header "string.h" : YES
Has header "sys/statvfs.h" : NO
Has header "sys/stat.h" : YES
Has header "sys/types.h" : YES
Has header "unistd.h" : NO
Has header "valgrind/valgrind.h" : NO
Checking for function "clock_gettime" : NO
Checking for function "getloadavg" : NO
Checking for function "getmntent_r" : NO
Checking for function "posix_memalign" : NO
Checking for function "pthread_set_name_np" : NO
Checking for function "sendmmsg" : NO
Checking for function "statvfs" : NO
Checking for function "strerror_r" : NO
Checking for function "strnlen" : YES
Checking whether type "struct nla_bitfield32" has member "value" : NO
Checking whether type "struct mmsghdr" has member "msg_len" : NO
Configuring config.h using configuration
Configuring string.h using configuration
Configuring stdio.h using configuration
Configuring sflow.map using configuration
Configuring openvswitch.map using configuration
Configuring ovsdb.map using configuration
Configuring ofproto.map using configuration
Configuring vtep.map using configuration
Configuring version.h using configuration
Configuring dirs.py using configuration
Configuring dirs.c using configuration

meson.build:267:4: ERROR: Include dir C:\pthreads\pthreads4w/include does not exist.

similarly for C:\pthreads\pthreads4w/lib

**Comment by smadaminov** [comment]
added check to the `meson.build` file so should be fixed now.
